config/routes.rb
Myapp::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :users
  
  resources 'articles', only: [:show, :new, :create, :edit, :update, :destroy] do 
  	resources 'comments'
  end
  
  get '/articles/:id/step/:step', to: 'articles#step', as: :step_article
  get '/articles/:article_id/comments/new/:parent_id', to: 'comments#new', as: :new_comment

  root 'articles#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  validates :body, presence: true,
                    length: { minimum: 5 }
  has_many :comments, :as => :commentable, :dependent => :destroy
  has_ancestry
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
		@parent_id = params.delete(:parent_id)
		@commentable = find_commentable
		@comment = Comment.new(	:parent_id => @parent_id,
							   	:commentable_id => @commentable.id,
							   	:commentable_type => @commentable.class.to_s)
	end

	def create
		@commentable = find_commentable
		@comment = @commentable.comments.build(comment_params)
		@comment.user_id = current_user.id
		@comment.user_name = current_user.user_name
		if @comment.save
			flash[:notice] = "Successfully create comment."
			redirect_to article_path(params[:article_id])
		else
			flash[:errors_create_comment] = @comment.errors.full_messages
			redirect_to article_path(params[:article_id])
		end
	end

	def update
		@comment = Comment.find(params[:id])

		if @comment.update(comment_params_edit)
			redirect_to article_path(params[:article_id])
		else
			flash[:comment_id] = @comment.id
			flash[:errors_edit_comment] = @comment.errors.full_messages
			redirect_to article_path(params[:article_id])
		end
	end

	def destroy
		@comment = Comment.find(params[:id])
	    @comment.destroy
	 
	    redirect_to article_path(params[:article_id])
	end

	private
	def comment_params
		params.require(:comment).permit(:body, :user_id, :parent_id)
	end

	def comment_params_edit
		params.require(:comment).permit(:body)
	end

	def find_commentable
		params.each do |name, value|
			if name =~ /(.+)_id$/
				return $1.classify.constantize.find(value)
			end
		end
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
	def nested_comments(comments)
		comments.map do |comment, sub_comments|
			content_tag(:div, render(comment), :class => "media", :style => "margin-left: 30px; padding: 4px;")
		end.join.html_safe
	end
end

app/views/comments/_comment.html.erb
<div class="showComment" comment_id = <%= comment.id%> >
	<strong><%= comment.user_name %>:</strong>
	<% if flash[:comment_id] == comment.id and flash[:errors_edit_comment] %>
		Error Edit Comment:
		<ul>
			<% flash[:errors_edit_comment].each  do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>
	<span style="padding: 4px; width: 70%;" class="label_comment" ><%= comment.body %></span><br/>
	<span style="padding: 4px; width: 70%; font-size: 15px; color: gray;" class="label_created_at" ><%= comment.created_at.strftime('%F %T') %></span>
	<span style="float: right;" >
		<%= link_to 'Reply', new_polymorphic_path([@commentable, Comment.new], :parent_id => comment, :article_id => @article) %>
		<% if current_user.id == comment.user_id %>
			<%= link_to 'Edit', "#", :class => "edit_link" %>
			<%= link_to 'Delete', article_comment_path(@article, comment), method: :delete,
          		data: { confirm: 'Are you sure?' }, :class => "delete_link" %>
		<% end %>
	</span>
</div>
<div class="editComment" style="display: none;" comment_id = <%= comment.id %> >
	<strong><%= comment.user_name %>:</strong>
	<% if current_user.id == comment.user_id %>
		
		<%= form_for(comment, :url => {:controller => "comments", :action => "update", :id => comment.id, :article_id => @article.id}, :method => :patch) do |f|%>
			<span style="padding: 4px;" class="textComment" ><%= f.text_area :body %></span>
			<span style="float: right;" ><%= submit_tag "Save" %></span>
  		<% end %>
	<% end %>
</div>
<%= nested_comments comment.children %>

app/views/comments/_comments.html.erb
<%= javascript_include_tag "application", "edit_comment", "data-turbolinks-track" => true %>
<%= csrf_meta_tags %>
<strong>Comments:</strong><br/>

app/views/comments/_edit.html.erb
<%= @comment %>

app/views/comments/_new.html.erb
<%= form_for([@article, @comment], local: true) do |form| %>
  
  <% if flash[:errors_create_comment] %>
      Error Add Comment:
      <ul>
        <% flash[:errors_create_comment].each  do |msg| %>
          <li><%= msg %></li>
              <% end %>
      </ul>
  <% end %>
  <p>
    <%= form.label current_user.user_name %>
  </p>
 
  <p>
    <%= form.label :comment %><br>
    <%= form.text_area :body %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/comments/new.html.erb
<%= form_for(@comment, :url => {:controller => "comments", :action => "create", :article_id => @commentable.id}, :method => :post, local: true) do |form| %>
  <%= form.hidden_field :parent_id %>
  <% if flash[:errors_create_comment] %>
      Error Add Comment:
      <ul>
        <% flash[:errors_create_comment].each  do |msg| %>
          <li><%= msg %></li>
              <% end %>
      </ul>
  <% end %>
  <p>
    <%= form.label current_user.user_name %>
  </p>
 
  <p>
    <%= form.label :comment %><br>
    <%= form.text_area :body, :row => 4 %>
  </p>
 
  <p>
    <%= form.submit "Post" %>
  </p>
 
<% end %>